image: Ubuntu2204   # образ для сборки, Ubuntu1804

stack: node 20  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  # - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild 20)
  - npm install
  # - npm install -g push-dir

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

# test_script:
#   - npm run lint  # скрипт тестирования
  # - npm run lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_PAT_TEST:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist --repo https://github.com/dmitrykhay/ahj-homeworks_anim.git
  # - npx push-dir --dir=dist --branch=gh-pages --force --verbose
